---
- name: Deploy Apache and PHP
  hosts: web_servers
  become: yes
  tasks:
    - name: "Step 1: Stop and Remove Nginx"
      apt:
        name: nginx
        state: absent

    - name: "Step 2: Install Apache and PHP"
      apt:
        name: 
          - apache2
          - php
          - libapache2-mod-php
        state: present
        update_cache: yes

    - name: "Step 3: Create your PHP page"
      copy:
        dest: /var/www/html/index.php
        content: |
          <?php
          echo "<div style='text-align: center; margin-top: 50px; font-family: Arial;'>";
          echo "<h1>Hello every </h1>";
          echo "<h3>Hostname: " . gethostname() . "</h3>";
          echo "<h3>IP Address: {{ ansible_host }}</h3>";
          echo "</div>";
          ?>

    - name: "Step 4: Clean up default index"
      file:
        path: /var/www/html/index.html
        state: absent

    - name: "Step 5: Make sure Apache is Up"
      service:
        name: apache2
        state: started
        enabled: yes

